// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBISJ16s2eRG9WF7IygRLoT42LI3vr6mV0',
    appId: '1:878893072706:web:3b1a339ea7e8232d2188db',
    messagingSenderId: '878893072706',
    projectId: 'rainbow-f0f87',
    authDomain: 'rainbow-f0f87.firebaseapp.com',
    storageBucket: 'rainbow-f0f87.firebasestorage.app',
    measurementId: 'G-G1SSGQ1HBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB63v3kKAA91KZCnPJiXjq5iFy4hIz0jhA',
    appId: '1:878893072706:android:ddefc420257f212e2188db',
    messagingSenderId: '878893072706',
    projectId: 'rainbow-f0f87',
    storageBucket: 'rainbow-f0f87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg8yyQ-L6yWrG6W1skETSOhrVL4rkragY',
    appId: '1:878893072706:ios:9867997f47cf7be72188db',
    messagingSenderId: '878893072706',
    projectId: 'rainbow-f0f87',
    storageBucket: 'rainbow-f0f87.firebasestorage.app',
    iosBundleId: 'com.foundercodes.rainbowPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg8yyQ-L6yWrG6W1skETSOhrVL4rkragY',
    appId: '1:878893072706:ios:9867997f47cf7be72188db',
    messagingSenderId: '878893072706',
    projectId: 'rainbow-f0f87',
    storageBucket: 'rainbow-f0f87.firebasestorage.app',
    iosBundleId: 'com.foundercodes.rainbowPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBISJ16s2eRG9WF7IygRLoT42LI3vr6mV0',
    appId: '1:878893072706:web:195b5a7093e834f52188db',
    messagingSenderId: '878893072706',
    projectId: 'rainbow-f0f87',
    authDomain: 'rainbow-f0f87.firebaseapp.com',
    storageBucket: 'rainbow-f0f87.firebasestorage.app',
    measurementId: 'G-TSTWGJVNPW',
  );
}
